// Autogenerated from CppHeaderCreator
// Custom Codegen for GORILLA TAG by chcoal
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: UnityEngine.Color32
#include "UnityEngine/Color32.hpp"
#include "beatsaber-hook/shared/utils/typedefs-string.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System::Collections::Generic
namespace System::Collections::Generic {
  // Forward declaring type: Dictionary`2<TKey, TValue>
  template<typename TKey, typename TValue>
  class Dictionary_2;
}
// Forward declaring namespace: UnityEngine
namespace UnityEngine {
  // Forward declaring type: Color
  struct Color;
}
// Completed forward declares
// Type namespace: UnityEngine.UIElements.StyleSheets
namespace UnityEngine::UIElements::StyleSheets {
  // Forward declaring type: StyleSheetColor
  class StyleSheetColor;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::UnityEngine::UIElements::StyleSheets::StyleSheetColor);
DEFINE_IL2CPP_ARG_TYPE(::UnityEngine::UIElements::StyleSheets::StyleSheetColor*, "UnityEngine.UIElements.StyleSheets", "StyleSheetColor");
// Type namespace: UnityEngine.UIElements.StyleSheets
namespace UnityEngine::UIElements::StyleSheets {
  // Size: 0x10
  #pragma pack(push, 1)
  // Autogenerated type: UnityEngine.UIElements.StyleSheets.StyleSheetColor
  // [TokenAttribute] Offset: FFFFFFFF
  class StyleSheetColor : public ::Il2CppObject {
    public:
    // Get static field: static private System.Collections.Generic.Dictionary`2<System.String,UnityEngine.Color32> s_NameToColor
    static ::System::Collections::Generic::Dictionary_2<::StringW, ::UnityEngine::Color32>* _get_s_NameToColor();
    // Set static field: static private System.Collections.Generic.Dictionary`2<System.String,UnityEngine.Color32> s_NameToColor
    static void _set_s_NameToColor(::System::Collections::Generic::Dictionary_2<::StringW, ::UnityEngine::Color32>* value);
    // static public System.Boolean TryGetColor(System.String name, out UnityEngine.Color color)
    // Offset: 0x55FB3F0
    static bool TryGetColor(::StringW name, ByRef<::UnityEngine::Color> color);
    // static private UnityEngine.Color32 HexToColor32(System.UInt32 color)
    // Offset: 0x55FEF70
    static ::UnityEngine::Color32 HexToColor32(uint color);
    // static private System.Void .cctor()
    // Offset: 0x55FEF84
    static void _cctor();
  }; // UnityEngine.UIElements.StyleSheets.StyleSheetColor
  #pragma pack(pop)
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: UnityEngine::UIElements::StyleSheets::StyleSheetColor::TryGetColor
// Il2CppName: TryGetColor
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<bool (*)(::StringW, ByRef<::UnityEngine::Color>)>(&UnityEngine::UIElements::StyleSheets::StyleSheetColor::TryGetColor)> {
  static const MethodInfo* get() {
    static auto* name = &::il2cpp_utils::GetClassFromName("System", "String")->byval_arg;
    static auto* color = &::il2cpp_utils::GetClassFromName("UnityEngine", "Color")->this_arg;
    return ::il2cpp_utils::FindMethod(classof(UnityEngine::UIElements::StyleSheets::StyleSheetColor*), "TryGetColor", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{name, color});
  }
};
// Writing MetadataGetter for method: UnityEngine::UIElements::StyleSheets::StyleSheetColor::HexToColor32
// Il2CppName: HexToColor32
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::UnityEngine::Color32 (*)(uint)>(&UnityEngine::UIElements::StyleSheets::StyleSheetColor::HexToColor32)> {
  static const MethodInfo* get() {
    static auto* color = &::il2cpp_utils::GetClassFromName("System", "UInt32")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(UnityEngine::UIElements::StyleSheets::StyleSheetColor*), "HexToColor32", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{color});
  }
};
// Writing MetadataGetter for method: UnityEngine::UIElements::StyleSheets::StyleSheetColor::_cctor
// Il2CppName: .cctor
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (*)()>(&UnityEngine::UIElements::StyleSheets::StyleSheetColor::_cctor)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(UnityEngine::UIElements::StyleSheets::StyleSheetColor*), ".cctor", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
