// Autogenerated from CppHeaderCreator
// Custom Codegen for GORILLA TAG by chcoal
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: Photon.Realtime.IInRoomCallbacks
#include "Photon/Realtime/IInRoomCallbacks.hpp"
// Including type: Photon.Realtime.IMatchmakingCallbacks
#include "Photon/Realtime/IMatchmakingCallbacks.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
#include "beatsaber-hook/shared/utils/typedefs-string.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: Photon::Realtime
namespace Photon::Realtime {
  // Forward declaring type: Player
  class Player;
  // Forward declaring type: FriendInfo
  class FriendInfo;
}
// Forward declaring namespace: System::Collections::Generic
namespace System::Collections::Generic {
  // Forward declaring type: List`1<T>
  template<typename T>
  class List_1;
}
// Forward declaring namespace: ExitGames::Client::Photon
namespace ExitGames::Client::Photon {
  // Forward declaring type: Hashtable
  class Hashtable;
}
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Forward declaring type: PhotonUserCache
  class PhotonUserCache;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::GlobalNamespace::PhotonUserCache);
DEFINE_IL2CPP_ARG_TYPE(::GlobalNamespace::PhotonUserCache*, "", "PhotonUserCache");
// Type namespace: 
namespace GlobalNamespace {
  // Size: 0x10
  #pragma pack(push, 1)
  // Autogenerated type: PhotonUserCache
  // [TokenAttribute] Offset: FFFFFFFF
  class PhotonUserCache : public ::Il2CppObject/*, public ::Photon::Realtime::IInRoomCallbacks, public ::Photon::Realtime::IMatchmakingCallbacks*/ {
    public:
    // Creating interface conversion operator: operator ::Photon::Realtime::IInRoomCallbacks
    operator ::Photon::Realtime::IInRoomCallbacks() noexcept {
      return *reinterpret_cast<::Photon::Realtime::IInRoomCallbacks*>(this);
    }
    // Creating interface conversion operator: operator ::Photon::Realtime::IMatchmakingCallbacks
    operator ::Photon::Realtime::IMatchmakingCallbacks() noexcept {
      return *reinterpret_cast<::Photon::Realtime::IMatchmakingCallbacks*>(this);
    }
    // private System.Void Photon.Realtime.IInRoomCallbacks.OnPlayerEnteredRoom(Photon.Realtime.Player newPlayer)
    // Offset: 0x275B8F0
    void Photon_Realtime_IInRoomCallbacks_OnPlayerEnteredRoom(::Photon::Realtime::Player* newPlayer);
    // private System.Void Photon.Realtime.IMatchmakingCallbacks.OnJoinedRoom()
    // Offset: 0x275B8F4
    void Photon_Realtime_IMatchmakingCallbacks_OnJoinedRoom();
    // private System.Void Photon.Realtime.IMatchmakingCallbacks.OnLeftRoom()
    // Offset: 0x275B8F8
    void Photon_Realtime_IMatchmakingCallbacks_OnLeftRoom();
    // private System.Void Photon.Realtime.IInRoomCallbacks.OnPlayerLeftRoom(Photon.Realtime.Player player)
    // Offset: 0x275B8FC
    void Photon_Realtime_IInRoomCallbacks_OnPlayerLeftRoom(::Photon::Realtime::Player* player);
    // private System.Void Photon.Realtime.IMatchmakingCallbacks.OnCreateRoomFailed(System.Int16 returnCode, System.String message)
    // Offset: 0x275B900
    void Photon_Realtime_IMatchmakingCallbacks_OnCreateRoomFailed(int16_t returnCode, ::StringW message);
    // private System.Void Photon.Realtime.IMatchmakingCallbacks.OnJoinRoomFailed(System.Int16 returnCode, System.String message)
    // Offset: 0x275B904
    void Photon_Realtime_IMatchmakingCallbacks_OnJoinRoomFailed(int16_t returnCode, ::StringW message);
    // private System.Void Photon.Realtime.IMatchmakingCallbacks.OnCreatedRoom()
    // Offset: 0x275B908
    void Photon_Realtime_IMatchmakingCallbacks_OnCreatedRoom();
    // private System.Void Photon.Realtime.IMatchmakingCallbacks.OnPreLeavingRoom()
    // Offset: 0x275B90C
    void Photon_Realtime_IMatchmakingCallbacks_OnPreLeavingRoom();
    // private System.Void Photon.Realtime.IMatchmakingCallbacks.OnJoinRandomFailed(System.Int16 returnCode, System.String message)
    // Offset: 0x275B910
    void Photon_Realtime_IMatchmakingCallbacks_OnJoinRandomFailed(int16_t returnCode, ::StringW message);
    // private System.Void Photon.Realtime.IMatchmakingCallbacks.OnFriendListUpdate(System.Collections.Generic.List`1<Photon.Realtime.FriendInfo> friendList)
    // Offset: 0x275B914
    void Photon_Realtime_IMatchmakingCallbacks_OnFriendListUpdate(::System::Collections::Generic::List_1<::Photon::Realtime::FriendInfo*>* friendList);
    // private System.Void Photon.Realtime.IInRoomCallbacks.OnRoomPropertiesUpdate(ExitGames.Client.Photon.Hashtable changedProperties)
    // Offset: 0x275B918
    void Photon_Realtime_IInRoomCallbacks_OnRoomPropertiesUpdate(::ExitGames::Client::Photon::Hashtable* changedProperties);
    // private System.Void Photon.Realtime.IInRoomCallbacks.OnPlayerPropertiesUpdate(Photon.Realtime.Player player, ExitGames.Client.Photon.Hashtable changedProperties)
    // Offset: 0x275B91C
    void Photon_Realtime_IInRoomCallbacks_OnPlayerPropertiesUpdate(::Photon::Realtime::Player* player, ::ExitGames::Client::Photon::Hashtable* changedProperties);
    // private System.Void Photon.Realtime.IInRoomCallbacks.OnMasterClientSwitched(Photon.Realtime.Player newMasterClient)
    // Offset: 0x275B920
    void Photon_Realtime_IInRoomCallbacks_OnMasterClientSwitched(::Photon::Realtime::Player* newMasterClient);
    // public System.Void .ctor()
    // Offset: 0x275B924
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static PhotonUserCache* New_ctor() {
      static auto ___internal__logger = ::Logger::get().WithContext("::GlobalNamespace::PhotonUserCache::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<PhotonUserCache*, creationType>()));
    }
  }; // PhotonUserCache
  #pragma pack(pop)
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: GlobalNamespace::PhotonUserCache::Photon_Realtime_IInRoomCallbacks_OnPlayerEnteredRoom
// Il2CppName: Photon.Realtime.IInRoomCallbacks.OnPlayerEnteredRoom
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (GlobalNamespace::PhotonUserCache::*)(::Photon::Realtime::Player*)>(&GlobalNamespace::PhotonUserCache::Photon_Realtime_IInRoomCallbacks_OnPlayerEnteredRoom)> {
  static const MethodInfo* get() {
    static auto* newPlayer = &::il2cpp_utils::GetClassFromName("Photon.Realtime", "Player")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(GlobalNamespace::PhotonUserCache*), "Photon.Realtime.IInRoomCallbacks.OnPlayerEnteredRoom", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{newPlayer});
  }
};
// Writing MetadataGetter for method: GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnJoinedRoom
// Il2CppName: Photon.Realtime.IMatchmakingCallbacks.OnJoinedRoom
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (GlobalNamespace::PhotonUserCache::*)()>(&GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnJoinedRoom)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(GlobalNamespace::PhotonUserCache*), "Photon.Realtime.IMatchmakingCallbacks.OnJoinedRoom", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnLeftRoom
// Il2CppName: Photon.Realtime.IMatchmakingCallbacks.OnLeftRoom
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (GlobalNamespace::PhotonUserCache::*)()>(&GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnLeftRoom)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(GlobalNamespace::PhotonUserCache*), "Photon.Realtime.IMatchmakingCallbacks.OnLeftRoom", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: GlobalNamespace::PhotonUserCache::Photon_Realtime_IInRoomCallbacks_OnPlayerLeftRoom
// Il2CppName: Photon.Realtime.IInRoomCallbacks.OnPlayerLeftRoom
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (GlobalNamespace::PhotonUserCache::*)(::Photon::Realtime::Player*)>(&GlobalNamespace::PhotonUserCache::Photon_Realtime_IInRoomCallbacks_OnPlayerLeftRoom)> {
  static const MethodInfo* get() {
    static auto* player = &::il2cpp_utils::GetClassFromName("Photon.Realtime", "Player")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(GlobalNamespace::PhotonUserCache*), "Photon.Realtime.IInRoomCallbacks.OnPlayerLeftRoom", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{player});
  }
};
// Writing MetadataGetter for method: GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnCreateRoomFailed
// Il2CppName: Photon.Realtime.IMatchmakingCallbacks.OnCreateRoomFailed
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (GlobalNamespace::PhotonUserCache::*)(int16_t, ::StringW)>(&GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnCreateRoomFailed)> {
  static const MethodInfo* get() {
    static auto* returnCode = &::il2cpp_utils::GetClassFromName("System", "Int16")->byval_arg;
    static auto* message = &::il2cpp_utils::GetClassFromName("System", "String")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(GlobalNamespace::PhotonUserCache*), "Photon.Realtime.IMatchmakingCallbacks.OnCreateRoomFailed", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{returnCode, message});
  }
};
// Writing MetadataGetter for method: GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnJoinRoomFailed
// Il2CppName: Photon.Realtime.IMatchmakingCallbacks.OnJoinRoomFailed
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (GlobalNamespace::PhotonUserCache::*)(int16_t, ::StringW)>(&GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnJoinRoomFailed)> {
  static const MethodInfo* get() {
    static auto* returnCode = &::il2cpp_utils::GetClassFromName("System", "Int16")->byval_arg;
    static auto* message = &::il2cpp_utils::GetClassFromName("System", "String")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(GlobalNamespace::PhotonUserCache*), "Photon.Realtime.IMatchmakingCallbacks.OnJoinRoomFailed", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{returnCode, message});
  }
};
// Writing MetadataGetter for method: GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnCreatedRoom
// Il2CppName: Photon.Realtime.IMatchmakingCallbacks.OnCreatedRoom
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (GlobalNamespace::PhotonUserCache::*)()>(&GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnCreatedRoom)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(GlobalNamespace::PhotonUserCache*), "Photon.Realtime.IMatchmakingCallbacks.OnCreatedRoom", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnPreLeavingRoom
// Il2CppName: Photon.Realtime.IMatchmakingCallbacks.OnPreLeavingRoom
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (GlobalNamespace::PhotonUserCache::*)()>(&GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnPreLeavingRoom)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(GlobalNamespace::PhotonUserCache*), "Photon.Realtime.IMatchmakingCallbacks.OnPreLeavingRoom", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnJoinRandomFailed
// Il2CppName: Photon.Realtime.IMatchmakingCallbacks.OnJoinRandomFailed
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (GlobalNamespace::PhotonUserCache::*)(int16_t, ::StringW)>(&GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnJoinRandomFailed)> {
  static const MethodInfo* get() {
    static auto* returnCode = &::il2cpp_utils::GetClassFromName("System", "Int16")->byval_arg;
    static auto* message = &::il2cpp_utils::GetClassFromName("System", "String")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(GlobalNamespace::PhotonUserCache*), "Photon.Realtime.IMatchmakingCallbacks.OnJoinRandomFailed", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{returnCode, message});
  }
};
// Writing MetadataGetter for method: GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnFriendListUpdate
// Il2CppName: Photon.Realtime.IMatchmakingCallbacks.OnFriendListUpdate
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (GlobalNamespace::PhotonUserCache::*)(::System::Collections::Generic::List_1<::Photon::Realtime::FriendInfo*>*)>(&GlobalNamespace::PhotonUserCache::Photon_Realtime_IMatchmakingCallbacks_OnFriendListUpdate)> {
  static const MethodInfo* get() {
    static auto* friendList = &::il2cpp_utils::MakeGeneric(::il2cpp_utils::GetClassFromName("System.Collections.Generic", "List`1"), ::std::vector<const Il2CppClass*>{::il2cpp_utils::GetClassFromName("Photon.Realtime", "FriendInfo")})->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(GlobalNamespace::PhotonUserCache*), "Photon.Realtime.IMatchmakingCallbacks.OnFriendListUpdate", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{friendList});
  }
};
// Writing MetadataGetter for method: GlobalNamespace::PhotonUserCache::Photon_Realtime_IInRoomCallbacks_OnRoomPropertiesUpdate
// Il2CppName: Photon.Realtime.IInRoomCallbacks.OnRoomPropertiesUpdate
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (GlobalNamespace::PhotonUserCache::*)(::ExitGames::Client::Photon::Hashtable*)>(&GlobalNamespace::PhotonUserCache::Photon_Realtime_IInRoomCallbacks_OnRoomPropertiesUpdate)> {
  static const MethodInfo* get() {
    static auto* changedProperties = &::il2cpp_utils::GetClassFromName("ExitGames.Client.Photon", "Hashtable")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(GlobalNamespace::PhotonUserCache*), "Photon.Realtime.IInRoomCallbacks.OnRoomPropertiesUpdate", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{changedProperties});
  }
};
// Writing MetadataGetter for method: GlobalNamespace::PhotonUserCache::Photon_Realtime_IInRoomCallbacks_OnPlayerPropertiesUpdate
// Il2CppName: Photon.Realtime.IInRoomCallbacks.OnPlayerPropertiesUpdate
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (GlobalNamespace::PhotonUserCache::*)(::Photon::Realtime::Player*, ::ExitGames::Client::Photon::Hashtable*)>(&GlobalNamespace::PhotonUserCache::Photon_Realtime_IInRoomCallbacks_OnPlayerPropertiesUpdate)> {
  static const MethodInfo* get() {
    static auto* player = &::il2cpp_utils::GetClassFromName("Photon.Realtime", "Player")->byval_arg;
    static auto* changedProperties = &::il2cpp_utils::GetClassFromName("ExitGames.Client.Photon", "Hashtable")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(GlobalNamespace::PhotonUserCache*), "Photon.Realtime.IInRoomCallbacks.OnPlayerPropertiesUpdate", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{player, changedProperties});
  }
};
// Writing MetadataGetter for method: GlobalNamespace::PhotonUserCache::Photon_Realtime_IInRoomCallbacks_OnMasterClientSwitched
// Il2CppName: Photon.Realtime.IInRoomCallbacks.OnMasterClientSwitched
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (GlobalNamespace::PhotonUserCache::*)(::Photon::Realtime::Player*)>(&GlobalNamespace::PhotonUserCache::Photon_Realtime_IInRoomCallbacks_OnMasterClientSwitched)> {
  static const MethodInfo* get() {
    static auto* newMasterClient = &::il2cpp_utils::GetClassFromName("Photon.Realtime", "Player")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(GlobalNamespace::PhotonUserCache*), "Photon.Realtime.IInRoomCallbacks.OnMasterClientSwitched", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{newMasterClient});
  }
};
// Writing MetadataGetter for method: GlobalNamespace::PhotonUserCache::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
