// Autogenerated from CppHeaderCreator
// Custom Codegen for GORILLA TAG by chcoal
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
#include "beatsaber-hook/shared/utils/typedefs-string.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: String
  class String;
}
// Completed forward declares
// Type namespace: UnityEngine.InputSystem
namespace UnityEngine::InputSystem {
  // Forward declaring type: InputFeatureNames
  class InputFeatureNames;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::UnityEngine::InputSystem::InputFeatureNames);
DEFINE_IL2CPP_ARG_TYPE(::UnityEngine::InputSystem::InputFeatureNames*, "UnityEngine.InputSystem", "InputFeatureNames");
// Type namespace: UnityEngine.InputSystem
namespace UnityEngine::InputSystem {
  // Size: 0x10
  #pragma pack(push, 1)
  // Autogenerated type: UnityEngine.InputSystem.InputFeatureNames
  // [TokenAttribute] Offset: FFFFFFFF
  class InputFeatureNames : public ::Il2CppObject {
    public:
    // static field const value: static public System.String kRunPlayerUpdatesInEditMode
    static constexpr const char* kRunPlayerUpdatesInEditMode = "RUN_PLAYER_UPDATES_IN_EDIT_MODE";
    // Get static field: static public System.String kRunPlayerUpdatesInEditMode
    static ::StringW _get_kRunPlayerUpdatesInEditMode();
    // Set static field: static public System.String kRunPlayerUpdatesInEditMode
    static void _set_kRunPlayerUpdatesInEditMode(::StringW value);
    // static field const value: static public System.String kDisableUnityRemoteSupport
    static constexpr const char* kDisableUnityRemoteSupport = "DISABLE_UNITY_REMOTE_SUPPORT";
    // Get static field: static public System.String kDisableUnityRemoteSupport
    static ::StringW _get_kDisableUnityRemoteSupport();
    // Set static field: static public System.String kDisableUnityRemoteSupport
    static void _set_kDisableUnityRemoteSupport(::StringW value);
    // static field const value: static public System.String kUseWindowsGamingInputBackend
    static constexpr const char* kUseWindowsGamingInputBackend = "USE_WINDOWS_GAMING_INPUT_BACKEND";
    // Get static field: static public System.String kUseWindowsGamingInputBackend
    static ::StringW _get_kUseWindowsGamingInputBackend();
    // Set static field: static public System.String kUseWindowsGamingInputBackend
    static void _set_kUseWindowsGamingInputBackend(::StringW value);
    // static field const value: static public System.String kUseOptimizedControls
    static constexpr const char* kUseOptimizedControls = "USE_OPTIMIZED_CONTROLS";
    // Get static field: static public System.String kUseOptimizedControls
    static ::StringW _get_kUseOptimizedControls();
    // Set static field: static public System.String kUseOptimizedControls
    static void _set_kUseOptimizedControls(::StringW value);
    // static field const value: static public System.String kUseReadValueCaching
    static constexpr const char* kUseReadValueCaching = "USE_READ_VALUE_CACHING";
    // Get static field: static public System.String kUseReadValueCaching
    static ::StringW _get_kUseReadValueCaching();
    // Set static field: static public System.String kUseReadValueCaching
    static void _set_kUseReadValueCaching(::StringW value);
    // static field const value: static public System.String kParanoidReadValueCachingChecks
    static constexpr const char* kParanoidReadValueCachingChecks = "PARANOID_READ_VALUE_CACHING_CHECKS";
    // Get static field: static public System.String kParanoidReadValueCachingChecks
    static ::StringW _get_kParanoidReadValueCachingChecks();
    // Set static field: static public System.String kParanoidReadValueCachingChecks
    static void _set_kParanoidReadValueCachingChecks(::StringW value);
  }; // UnityEngine.InputSystem.InputFeatureNames
  #pragma pack(pop)
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
