// Autogenerated from CppHeaderCreator
// Custom Codegen for GORILLA TAG by chcoal
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: Unity.Burst.BurstString
#include "Unity/Burst/BurstString.hpp"
// Including type: System.ValueType
#include "System/ValueType.hpp"
// Completed includes
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
DEFINE_IL2CPP_ARG_TYPE(::Unity::Burst::BurstString::tFloatUnion64, "Unity.Burst", "BurstString/tFloatUnion64");
// Type namespace: Unity.Burst
namespace Unity::Burst {
  // WARNING Size may be invalid!
  // WARNING Layout: Explicit may not be correctly taken into account!
  // Autogenerated type: Unity.Burst.BurstString/tFloatUnion64
  // [TokenAttribute] Offset: FFFFFFFF
  struct BurstString::tFloatUnion64/*, public ::System::ValueType*/ {
    public:
    public:
    // public System.Double m_floatingPoint
    // Size: 0x8
    // Offset: 0x0
    double m_floatingPoint;
    // Field size check
    static_assert(sizeof(double) == 0x8);
    // public System.UInt64 m_integer
    // Size: 0x8
    // Offset: 0x0
    uint64_t m_integer;
    // Field size check
    static_assert(sizeof(uint64_t) == 0x8);
    public:
    // Creating value type constructor for type: tFloatUnion64
    constexpr tFloatUnion64(double m_floatingPoint_ = {}, uint64_t m_integer_ = {}) noexcept : m_floatingPoint{m_floatingPoint_}, m_integer{m_integer_} {}
    // Creating interface conversion operator: operator ::System::ValueType
    operator ::System::ValueType() noexcept {
      return *reinterpret_cast<::System::ValueType*>(this);
    }
    // Get instance field reference: public System.Double m_floatingPoint
    [[deprecated("Use field access instead!")]] double& dyn_m_floatingPoint();
    // Get instance field reference: public System.UInt64 m_integer
    [[deprecated("Use field access instead!")]] uint64_t& dyn_m_integer();
    // public System.Boolean IsNegative()
    // Offset: 0x5085120
    bool IsNegative();
    // public System.UInt32 GetExponent()
    // Offset: 0x5085108
    uint GetExponent();
    // public System.UInt64 GetMantissa()
    // Offset: 0x5085114
    uint64_t GetMantissa();
  }; // Unity.Burst.BurstString/tFloatUnion64
  // WARNING Not writing size check since size may be invalid!
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: Unity::Burst::BurstString::tFloatUnion64::IsNegative
// Il2CppName: IsNegative
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<bool (Unity::Burst::BurstString::tFloatUnion64::*)()>(&Unity::Burst::BurstString::tFloatUnion64::IsNegative)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Unity::Burst::BurstString::tFloatUnion64), "IsNegative", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Unity::Burst::BurstString::tFloatUnion64::GetExponent
// Il2CppName: GetExponent
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<uint (Unity::Burst::BurstString::tFloatUnion64::*)()>(&Unity::Burst::BurstString::tFloatUnion64::GetExponent)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Unity::Burst::BurstString::tFloatUnion64), "GetExponent", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Unity::Burst::BurstString::tFloatUnion64::GetMantissa
// Il2CppName: GetMantissa
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<uint64_t (Unity::Burst::BurstString::tFloatUnion64::*)()>(&Unity::Burst::BurstString::tFloatUnion64::GetMantissa)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Unity::Burst::BurstString::tFloatUnion64), "GetMantissa", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
