// Autogenerated from CppHeaderCreator
// Custom Codegen for GORILLA TAG by chcoal
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: System.Attribute
#include "System/Attribute.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
#include "beatsaber-hook/shared/utils/typedefs-string.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: Type
  class Type;
}
// Completed forward declares
// Type namespace: System.ComponentModel
namespace System::ComponentModel {
  // Forward declaring type: EditorAttribute
  class EditorAttribute;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::System::ComponentModel::EditorAttribute);
DEFINE_IL2CPP_ARG_TYPE(::System::ComponentModel::EditorAttribute*, "System.ComponentModel", "EditorAttribute");
// Type namespace: System.ComponentModel
namespace System::ComponentModel {
  // Size: 0x28
  #pragma pack(push, 1)
  // Autogenerated type: System.ComponentModel.EditorAttribute
  // [TokenAttribute] Offset: FFFFFFFF
  // [AttributeUsageAttribute] Offset: FFFFFFFF
  class EditorAttribute : public ::System::Attribute {
    public:
    public:
    // private System.String _typeId
    // Size: 0x8
    // Offset: 0x10
    ::StringW typeId;
    // Field size check
    static_assert(sizeof(::StringW) == 0x8);
    // private readonly System.String <EditorBaseTypeName>k__BackingField
    // Size: 0x8
    // Offset: 0x18
    ::StringW EditorBaseTypeName;
    // Field size check
    static_assert(sizeof(::StringW) == 0x8);
    // private readonly System.String <EditorTypeName>k__BackingField
    // Size: 0x8
    // Offset: 0x20
    ::StringW EditorTypeName;
    // Field size check
    static_assert(sizeof(::StringW) == 0x8);
    public:
    // Get instance field reference: private System.String _typeId
    [[deprecated("Use field access instead!")]] ::StringW& dyn__typeId();
    // Get instance field reference: private readonly System.String <EditorBaseTypeName>k__BackingField
    [[deprecated("Use field access instead!")]] ::StringW& dyn_$EditorBaseTypeName$k__BackingField();
    // Get instance field reference: private readonly System.String <EditorTypeName>k__BackingField
    [[deprecated("Use field access instead!")]] ::StringW& dyn_$EditorTypeName$k__BackingField();
    // public System.Void .ctor()
    // Offset: 0x4F01F60
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static EditorAttribute* New_ctor() {
      static auto ___internal__logger = ::Logger::get().WithContext("::System::ComponentModel::EditorAttribute::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<EditorAttribute*, creationType>()));
    }
    // public System.Void .ctor(System.String typeName, System.String baseTypeName)
    // Offset: 0x4F01FD8
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static EditorAttribute* New_ctor(::StringW typeName, ::StringW baseTypeName) {
      static auto ___internal__logger = ::Logger::get().WithContext("::System::ComponentModel::EditorAttribute::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<EditorAttribute*, creationType>(typeName, baseTypeName)));
    }
    // public System.Void .ctor(System.String typeName, System.Type baseType)
    // Offset: 0x4F02080
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static EditorAttribute* New_ctor(::StringW typeName, ::System::Type* baseType) {
      static auto ___internal__logger = ::Logger::get().WithContext("::System::ComponentModel::EditorAttribute::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<EditorAttribute*, creationType>(typeName, baseType)));
    }
    // public System.Void .ctor(System.Type type, System.Type baseType)
    // Offset: 0x4F02140
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static EditorAttribute* New_ctor(::System::Type* type, ::System::Type* baseType) {
      static auto ___internal__logger = ::Logger::get().WithContext("::System::ComponentModel::EditorAttribute::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<EditorAttribute*, creationType>(type, baseType)));
    }
    // public System.String get_EditorBaseTypeName()
    // Offset: 0x4F021B8
    ::StringW get_EditorBaseTypeName();
    // public System.String get_EditorTypeName()
    // Offset: 0x4F021C0
    ::StringW get_EditorTypeName();
    // public override System.Object get_TypeId()
    // Offset: 0x4F021C8
    // Implemented from: System.Attribute
    // Base method: System.Object Attribute::get_TypeId()
    ::Il2CppObject* get_TypeId();
    // public override System.Boolean Equals(System.Object obj)
    // Offset: 0x4F02268
    // Implemented from: System.Attribute
    // Base method: System.Boolean Attribute::Equals(System.Object obj)
    bool Equals(::Il2CppObject* obj);
    // public override System.Int32 GetHashCode()
    // Offset: 0x4F0230C
    // Implemented from: System.Attribute
    // Base method: System.Int32 Attribute::GetHashCode()
    int GetHashCode();
  }; // System.ComponentModel.EditorAttribute
  #pragma pack(pop)
  static check_size<sizeof(EditorAttribute), 32 + sizeof(::StringW)> __System_ComponentModel_EditorAttributeSizeCheck;
  static_assert(sizeof(EditorAttribute) == 0x28);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: System::ComponentModel::EditorAttribute::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: System::ComponentModel::EditorAttribute::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: System::ComponentModel::EditorAttribute::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: System::ComponentModel::EditorAttribute::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: System::ComponentModel::EditorAttribute::get_EditorBaseTypeName
// Il2CppName: get_EditorBaseTypeName
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::StringW (System::ComponentModel::EditorAttribute::*)()>(&System::ComponentModel::EditorAttribute::get_EditorBaseTypeName)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::ComponentModel::EditorAttribute*), "get_EditorBaseTypeName", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::ComponentModel::EditorAttribute::get_EditorTypeName
// Il2CppName: get_EditorTypeName
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::StringW (System::ComponentModel::EditorAttribute::*)()>(&System::ComponentModel::EditorAttribute::get_EditorTypeName)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::ComponentModel::EditorAttribute*), "get_EditorTypeName", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::ComponentModel::EditorAttribute::get_TypeId
// Il2CppName: get_TypeId
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::Il2CppObject* (System::ComponentModel::EditorAttribute::*)()>(&System::ComponentModel::EditorAttribute::get_TypeId)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::ComponentModel::EditorAttribute*), "get_TypeId", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::ComponentModel::EditorAttribute::Equals
// Il2CppName: Equals
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<bool (System::ComponentModel::EditorAttribute::*)(::Il2CppObject*)>(&System::ComponentModel::EditorAttribute::Equals)> {
  static const MethodInfo* get() {
    static auto* obj = &::il2cpp_utils::GetClassFromName("System", "Object")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::ComponentModel::EditorAttribute*), "Equals", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{obj});
  }
};
// Writing MetadataGetter for method: System::ComponentModel::EditorAttribute::GetHashCode
// Il2CppName: GetHashCode
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<int (System::ComponentModel::EditorAttribute::*)()>(&System::ComponentModel::EditorAttribute::GetHashCode)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::ComponentModel::EditorAttribute*), "GetHashCode", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
