// Autogenerated from CppHeaderCreator
// Custom Codegen for GORILLA TAG by chcoal
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: Fusion.PropertyAttribute
#include "Fusion/PropertyAttribute.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
#include "beatsaber-hook/shared/utils/typedefs-string.hpp"
// Completed includes
// Type namespace: Fusion
namespace Fusion {
  // Forward declaring type: DefaultForPropertyAttribute
  class DefaultForPropertyAttribute;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::Fusion::DefaultForPropertyAttribute);
DEFINE_IL2CPP_ARG_TYPE(::Fusion::DefaultForPropertyAttribute*, "Fusion", "DefaultForPropertyAttribute");
// Type namespace: Fusion
namespace Fusion {
  // Size: 0x28
  #pragma pack(push, 1)
  // Autogenerated type: Fusion.DefaultForPropertyAttribute
  // [TokenAttribute] Offset: FFFFFFFF
  // [AttributeUsageAttribute] Offset: FFFFFFFF
  class DefaultForPropertyAttribute : public ::Fusion::PropertyAttribute {
    public:
    // Writing base type padding for base size: 0x14 to desired offset: 0x18
    char ___base_padding[0x4] = {};
    public:
    // private readonly System.String <PropertyName>k__BackingField
    // Size: 0x8
    // Offset: 0x18
    ::StringW PropertyName;
    // Field size check
    static_assert(sizeof(::StringW) == 0x8);
    // private readonly System.Int32 <WordOffset>k__BackingField
    // Size: 0x4
    // Offset: 0x20
    int WordOffset;
    // Field size check
    static_assert(sizeof(int) == 0x4);
    // private readonly System.Int32 <WordCount>k__BackingField
    // Size: 0x4
    // Offset: 0x24
    int WordCount;
    // Field size check
    static_assert(sizeof(int) == 0x4);
    public:
    // Deleting conversion operator: operator int
    constexpr operator int() const noexcept = delete;
    // Get instance field reference: private readonly System.String <PropertyName>k__BackingField
    [[deprecated("Use field access instead!")]] ::StringW& dyn_$PropertyName$k__BackingField();
    // Get instance field reference: private readonly System.Int32 <WordOffset>k__BackingField
    [[deprecated("Use field access instead!")]] int& dyn_$WordOffset$k__BackingField();
    // Get instance field reference: private readonly System.Int32 <WordCount>k__BackingField
    [[deprecated("Use field access instead!")]] int& dyn_$WordCount$k__BackingField();
    // public System.String get_PropertyName()
    // Offset: 0x2AFED74
    ::StringW get_PropertyName();
    // public System.Int32 get_WordOffset()
    // Offset: 0x2AFED7C
    int get_WordOffset();
    // public System.Int32 get_WordCount()
    // Offset: 0x2AFED84
    int get_WordCount();
    // public System.Void .ctor(System.String propertyName, System.Int32 wordOffset, System.Int32 wordCount)
    // Offset: 0x2AFED8C
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static DefaultForPropertyAttribute* New_ctor(::StringW propertyName, int wordOffset, int wordCount) {
      static auto ___internal__logger = ::Logger::get().WithContext("::Fusion::DefaultForPropertyAttribute::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<DefaultForPropertyAttribute*, creationType>(propertyName, wordOffset, wordCount)));
    }
  }; // Fusion.DefaultForPropertyAttribute
  #pragma pack(pop)
  static check_size<sizeof(DefaultForPropertyAttribute), 36 + sizeof(int)> __Fusion_DefaultForPropertyAttributeSizeCheck;
  static_assert(sizeof(DefaultForPropertyAttribute) == 0x28);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: Fusion::DefaultForPropertyAttribute::get_PropertyName
// Il2CppName: get_PropertyName
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::StringW (Fusion::DefaultForPropertyAttribute::*)()>(&Fusion::DefaultForPropertyAttribute::get_PropertyName)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Fusion::DefaultForPropertyAttribute*), "get_PropertyName", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Fusion::DefaultForPropertyAttribute::get_WordOffset
// Il2CppName: get_WordOffset
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<int (Fusion::DefaultForPropertyAttribute::*)()>(&Fusion::DefaultForPropertyAttribute::get_WordOffset)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Fusion::DefaultForPropertyAttribute*), "get_WordOffset", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Fusion::DefaultForPropertyAttribute::get_WordCount
// Il2CppName: get_WordCount
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<int (Fusion::DefaultForPropertyAttribute::*)()>(&Fusion::DefaultForPropertyAttribute::get_WordCount)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Fusion::DefaultForPropertyAttribute*), "get_WordCount", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Fusion::DefaultForPropertyAttribute::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
